// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.1
// source: protocol/msg.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_Push  Action = 0
	Action_Pull  Action = 1
	Action_Sub   Action = 2
	Action_UnSub Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "Push",
		1: "Pull",
		2: "Sub",
		3: "UnSub",
	}
	Action_value = map[string]int32{
		"Push":  0,
		"Pull":  1,
		"Sub":   2,
		"UnSub": 3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_msg_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_protocol_msg_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_protocol_msg_proto_rawDescGZIP(), []int{0}
}

type Mode int32

const (
	Mode_P2P    Mode = 0
	Mode_PubSub Mode = 1
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "P2P",
		1: "PubSub",
	}
	Mode_value = map[string]int32{
		"P2P":    0,
		"PubSub": 1,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_msg_proto_enumTypes[1].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_protocol_msg_proto_enumTypes[1]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_protocol_msg_proto_rawDescGZIP(), []int{1}
}

type MQRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action   Action `protobuf:"varint,1,opt,name=action,proto3,enum=protocol.Action" json:"action,omitempty"`
	Mode     Mode   `protobuf:"varint,2,opt,name=mode,proto3,enum=protocol.Mode" json:"mode,omitempty"`
	Sender   string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Payload  []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Pulls    uint64 `protobuf:"varint,6,opt,name=pulls,proto3" json:"pulls,omitempty"`
}

func (x *MQRequest) Reset() {
	*x = MQRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQRequest) ProtoMessage() {}

func (x *MQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQRequest.ProtoReflect.Descriptor instead.
func (*MQRequest) Descriptor() ([]byte, []int) {
	return file_protocol_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MQRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_Push
}

func (x *MQRequest) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_P2P
}

func (x *MQRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *MQRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *MQRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MQRequest) GetPulls() uint64 {
	if x != nil {
		return x.Pulls
	}
	return 0
}

// MQMessage
type MQMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 源，生产者
	Source  string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *MQMessage) Reset() {
	*x = MQMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MQMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQMessage) ProtoMessage() {}

func (x *MQMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQMessage.ProtoReflect.Descriptor instead.
func (*MQMessage) Descriptor() ([]byte, []int) {
	return file_protocol_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MQMessage) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MQMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type MQResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message   *MQMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Remaining uint64     `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Error     string     `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MQResponse) Reset() {
	*x = MQResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQResponse) ProtoMessage() {}

func (x *MQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQResponse.ProtoReflect.Descriptor instead.
func (*MQResponse) Descriptor() ([]byte, []int) {
	return file_protocol_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MQResponse) GetMessage() *MQMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MQResponse) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *MQResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MQMultiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Responses []*MQResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	Remaining uint64        `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Error     string        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MQMultiResponse) Reset() {
	*x = MQMultiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MQMultiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MQMultiResponse) ProtoMessage() {}

func (x *MQMultiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MQMultiResponse.ProtoReflect.Descriptor instead.
func (*MQMultiResponse) Descriptor() ([]byte, []int) {
	return file_protocol_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MQMultiResponse) GetResponses() []*MQResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *MQMultiResponse) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *MQMultiResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protocol_msg_proto protoreflect.FileDescriptor

var file_protocol_msg_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x73, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xbd,
	0x01, 0x0a, 0x09, 0x4d, 0x51, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x6c, 0x6c,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x70, 0x75, 0x6c, 0x6c, 0x73, 0x22, 0x3d,
	0x0a, 0x09, 0x4d, 0x51, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x6f, 0x0a,
	0x0a, 0x4d, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x51, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65,
	0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72,
	0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x79,
	0x0a, 0x0f, 0x4d, 0x51, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x32, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x4d, 0x51, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x09, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69,
	0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e,
	0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2a, 0x30, 0x0a, 0x06, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x50, 0x75, 0x6c, 0x6c, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x75, 0x62, 0x10, 0x02,
	0x12, 0x09, 0x0a, 0x05, 0x55, 0x6e, 0x53, 0x75, 0x62, 0x10, 0x03, 0x2a, 0x1b, 0x0a, 0x04, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x32, 0x50, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x50, 0x75, 0x62, 0x53, 0x75, 0x62, 0x10, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_msg_proto_rawDescOnce sync.Once
	file_protocol_msg_proto_rawDescData = file_protocol_msg_proto_rawDesc
)

func file_protocol_msg_proto_rawDescGZIP() []byte {
	file_protocol_msg_proto_rawDescOnce.Do(func() {
		file_protocol_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_msg_proto_rawDescData)
	})
	return file_protocol_msg_proto_rawDescData
}

var file_protocol_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protocol_msg_proto_goTypes = []interface{}{
	(Action)(0),             // 0: protocol.Action
	(Mode)(0),               // 1: protocol.Mode
	(*MQRequest)(nil),       // 2: protocol.MQRequest
	(*MQMessage)(nil),       // 3: protocol.MQMessage
	(*MQResponse)(nil),      // 4: protocol.MQResponse
	(*MQMultiResponse)(nil), // 5: protocol.MQMultiResponse
}
var file_protocol_msg_proto_depIdxs = []int32{
	0, // 0: protocol.MQRequest.action:type_name -> protocol.Action
	1, // 1: protocol.MQRequest.mode:type_name -> protocol.Mode
	3, // 2: protocol.MQResponse.message:type_name -> protocol.MQMessage
	4, // 3: protocol.MQMultiResponse.responses:type_name -> protocol.MQResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protocol_msg_proto_init() }
func file_protocol_msg_proto_init() {
	if File_protocol_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MQRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MQMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MQResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MQMultiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_msg_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_msg_proto_goTypes,
		DependencyIndexes: file_protocol_msg_proto_depIdxs,
		EnumInfos:         file_protocol_msg_proto_enumTypes,
		MessageInfos:      file_protocol_msg_proto_msgTypes,
	}.Build()
	File_protocol_msg_proto = out.File
	file_protocol_msg_proto_rawDesc = nil
	file_protocol_msg_proto_goTypes = nil
	file_protocol_msg_proto_depIdxs = nil
}
